package net;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import viaversion.viaversion.api.entities.EntityType;

public enum a_4 implements EntityType {
   ENTITY(-1),
   AREA_EFFECT_CLOUD(0, ENTITY),
   END_CRYSTAL(16, ENTITY),
   EVOKER_FANGS(20, ENTITY),
   EXPERIENCE_ORB(22, ENTITY),
   EYE_OF_ENDER(23, ENTITY),
   FALLING_BLOCK(24, ENTITY),
   FIREWORK_ROCKET(25, ENTITY),
   ITEM(32, ENTITY),
   LLAMA_SPIT(37, ENTITY),
   TNT(55, ENTITY),
   SHULKER_BULLET(60, ENTITY),
   FISHING_BOBBER(93, ENTITY),
   LIVINGENTITY(-1, ENTITY),
   ARMOR_STAND(1, LIVINGENTITY),
   PLAYER(92, LIVINGENTITY),
   ABSTRACT_INSENTIENT(-1, LIVINGENTITY),
   ENDER_DRAGON(17, ABSTRACT_INSENTIENT),
   ABSTRACT_CREATURE(-1, ABSTRACT_INSENTIENT),
   ABSTRACT_AGEABLE(-1, ABSTRACT_CREATURE),
   VILLAGER(79, ABSTRACT_AGEABLE),
   ABSTRACT_ANIMAL(-1, ABSTRACT_AGEABLE),
   CHICKEN(7, ABSTRACT_ANIMAL),
   COW(9, ABSTRACT_ANIMAL),
   MOOSHROOM(47, COW),
   PIG(51, ABSTRACT_ANIMAL),
   POLAR_BEAR(54, ABSTRACT_ANIMAL),
   RABBIT(56, ABSTRACT_ANIMAL),
   SHEEP(58, ABSTRACT_ANIMAL),
   TURTLE(73, ABSTRACT_ANIMAL),
   ABSTRACT_TAMEABLE_ANIMAL(-1, ABSTRACT_ANIMAL),
   OCELOT(48, ABSTRACT_TAMEABLE_ANIMAL),
   WOLF(86, ABSTRACT_TAMEABLE_ANIMAL),
   ABSTRACT_PARROT(-1, ABSTRACT_TAMEABLE_ANIMAL),
   PARROT(50, ABSTRACT_PARROT),
   ABSTRACT_HORSE(-1, ABSTRACT_ANIMAL),
   CHESTED_HORSE(-1, ABSTRACT_HORSE),
   DONKEY(11, CHESTED_HORSE),
   MULE(46, CHESTED_HORSE),
   LLAMA(36, CHESTED_HORSE),
   HORSE(29, ABSTRACT_HORSE),
   SKELETON_HORSE(63, ABSTRACT_HORSE),
   ZOMBIE_HORSE(88, ABSTRACT_HORSE),
   ABSTRACT_GOLEM(-1, ABSTRACT_CREATURE),
   SNOW_GOLEM(66, ABSTRACT_GOLEM),
   IRON_GOLEM(80, ABSTRACT_GOLEM),
   SHULKER(59, ABSTRACT_GOLEM),
   ABSTRACT_FISHES(-1, ABSTRACT_CREATURE),
   COD(8, ABSTRACT_FISHES),
   PUFFERFISH(52, ABSTRACT_FISHES),
   SALMON(57, ABSTRACT_FISHES),
   TROPICAL_FISH(72, ABSTRACT_FISHES),
   ABSTRACT_MONSTER(-1, ABSTRACT_CREATURE),
   BLAZE(4, ABSTRACT_MONSTER),
   CREEPER(10, ABSTRACT_MONSTER),
   ENDERMITE(19, ABSTRACT_MONSTER),
   ENDERMAN(18, ABSTRACT_MONSTER),
   GIANT(27, ABSTRACT_MONSTER),
   SILVERFISH(61, ABSTRACT_MONSTER),
   VEX(78, ABSTRACT_MONSTER),
   WITCH(82, ABSTRACT_MONSTER),
   WITHER(83, ABSTRACT_MONSTER),
   ABSTRACT_ILLAGER_BASE(-1, ABSTRACT_MONSTER),
   ABSTRACT_EVO_ILLU_ILLAGER(-1, ABSTRACT_ILLAGER_BASE),
   EVOKER(21, ABSTRACT_EVO_ILLU_ILLAGER),
   ILLUSIONER(31, ABSTRACT_EVO_ILLU_ILLAGER),
   VINDICATOR(81, ABSTRACT_ILLAGER_BASE),
   ABSTRACT_SKELETON(-1, ABSTRACT_MONSTER),
   SKELETON(62, ABSTRACT_SKELETON),
   STRAY(71, ABSTRACT_SKELETON),
   WITHER_SKELETON(84, ABSTRACT_SKELETON),
   GUARDIAN(28, ABSTRACT_MONSTER),
   ELDER_GUARDIAN(15, GUARDIAN),
   SPIDER(69, ABSTRACT_MONSTER),
   CAVE_SPIDER(6, SPIDER),
   ZOMBIE(87, ABSTRACT_MONSTER),
   DROWNED(14, ZOMBIE),
   HUSK(30, ZOMBIE),
   ZOMBIE_PIGMAN(53, ZOMBIE),
   ZOMBIE_VILLAGER(89, ZOMBIE),
   ABSTRACT_FLYING(-1, ABSTRACT_INSENTIENT),
   GHAST(26, ABSTRACT_FLYING),
   PHANTOM(90, ABSTRACT_FLYING),
   ABSTRACT_AMBIENT(-1, ABSTRACT_INSENTIENT),
   BAT(3, ABSTRACT_AMBIENT),
   ABSTRACT_WATERMOB(-1, ABSTRACT_INSENTIENT),
   SQUID(70, ABSTRACT_WATERMOB),
   DOLPHIN(12, ABSTRACT_WATERMOB),
   SLIME(64, ABSTRACT_INSENTIENT),
   MAGMA_CUBE(38, SLIME),
   ABSTRACT_HANGING(-1, ENTITY),
   LEASH_KNOT(35, ABSTRACT_HANGING),
   ITEM_FRAME(33, ABSTRACT_HANGING),
   PAINTING(49, ABSTRACT_HANGING),
   ABSTRACT_LIGHTNING(-1, ENTITY),
   LIGHTNING_BOLT(91, ABSTRACT_LIGHTNING),
   ABSTRACT_ARROW(-1, ENTITY),
   ARROW(2, ABSTRACT_ARROW),
   SPECTRAL_ARROW(68, ABSTRACT_ARROW),
   TRIDENT(94, ABSTRACT_ARROW),
   ABSTRACT_FIREBALL(-1, ENTITY),
   DRAGON_FIREBALL(13, ABSTRACT_FIREBALL),
   FIREBALL(34, ABSTRACT_FIREBALL),
   SMALL_FIREBALL(65, ABSTRACT_FIREBALL),
   WITHER_SKULL(85, ABSTRACT_FIREBALL),
   PROJECTILE_ABSTRACT(-1, ENTITY),
   SNOWBALL(67, PROJECTILE_ABSTRACT),
   ENDER_PEARL(75, PROJECTILE_ABSTRACT),
   EGG(74, PROJECTILE_ABSTRACT),
   POTION(77, PROJECTILE_ABSTRACT),
   EXPERIENCE_BOTTLE(76, PROJECTILE_ABSTRACT),
   MINECART_ABSTRACT(-1, ENTITY),
   CHESTED_MINECART_ABSTRACT(-1, MINECART_ABSTRACT),
   CHEST_MINECART(40, CHESTED_MINECART_ABSTRACT),
   HOPPER_MINECART(43, CHESTED_MINECART_ABSTRACT),
   MINECART(39, MINECART_ABSTRACT),
   FURNACE_MINECART(42, MINECART_ABSTRACT),
   COMMAND_BLOCK_MINECART(41, MINECART_ABSTRACT),
   TNT_MINECART(45, MINECART_ABSTRACT),
   SPAWNER_MINECART(44, MINECART_ABSTRACT),
   BOAT(5, ENTITY);

   private static final Map e = new HashMap();
   private final int d;
   private final a_4 f;
   private static final a_4[] c = new a_4[]{ENTITY, AREA_EFFECT_CLOUD, END_CRYSTAL, EVOKER_FANGS, EXPERIENCE_ORB, EYE_OF_ENDER, FALLING_BLOCK, FIREWORK_ROCKET, ITEM, LLAMA_SPIT, TNT, SHULKER_BULLET, FISHING_BOBBER, LIVINGENTITY, ARMOR_STAND, PLAYER, ABSTRACT_INSENTIENT, ENDER_DRAGON, ABSTRACT_CREATURE, ABSTRACT_AGEABLE, VILLAGER, ABSTRACT_ANIMAL, CHICKEN, COW, MOOSHROOM, PIG, POLAR_BEAR, RABBIT, SHEEP, TURTLE, ABSTRACT_TAMEABLE_ANIMAL, OCELOT, WOLF, ABSTRACT_PARROT, PARROT, ABSTRACT_HORSE, CHESTED_HORSE, DONKEY, MULE, LLAMA, HORSE, SKELETON_HORSE, ZOMBIE_HORSE, ABSTRACT_GOLEM, SNOW_GOLEM, IRON_GOLEM, SHULKER, ABSTRACT_FISHES, COD, PUFFERFISH, SALMON, TROPICAL_FISH, ABSTRACT_MONSTER, BLAZE, CREEPER, ENDERMITE, ENDERMAN, GIANT, SILVERFISH, VEX, WITCH, WITHER, ABSTRACT_ILLAGER_BASE, ABSTRACT_EVO_ILLU_ILLAGER, EVOKER, ILLUSIONER, VINDICATOR, ABSTRACT_SKELETON, SKELETON, STRAY, WITHER_SKELETON, GUARDIAN, ELDER_GUARDIAN, SPIDER, CAVE_SPIDER, ZOMBIE, DROWNED, HUSK, ZOMBIE_PIGMAN, ZOMBIE_VILLAGER, ABSTRACT_FLYING, GHAST, PHANTOM, ABSTRACT_AMBIENT, BAT, ABSTRACT_WATERMOB, SQUID, DOLPHIN, SLIME, MAGMA_CUBE, ABSTRACT_HANGING, LEASH_KNOT, ITEM_FRAME, PAINTING, ABSTRACT_LIGHTNING, LIGHTNING_BOLT, ABSTRACT_ARROW, ARROW, SPECTRAL_ARROW, TRIDENT, ABSTRACT_FIREBALL, DRAGON_FIREBALL, FIREBALL, SMALL_FIREBALL, WITHER_SKULL, PROJECTILE_ABSTRACT, SNOWBALL, ENDER_PEARL, EGG, POTION, EXPERIENCE_BOTTLE, MINECART_ABSTRACT, CHESTED_MINECART_ABSTRACT, CHEST_MINECART, HOPPER_MINECART, MINECART, FURNACE_MINECART, COMMAND_BLOCK_MINECART, TNT_MINECART, SPAWNER_MINECART, BOAT};
   private static boolean b;

   private a_4(int var3) {
      this.d = var3;
      this.f = null;
   }

   private a_4(int var3, a_4 var4) {
      this.d = var3;
      this.f = var4;
   }

   public int getId() {
      return this.d;
   }

   public a_4 b() {
      return this.f;
   }

   public static Optional a(int var0) {
      return var0 == -1?Optional.empty():Optional.ofNullable(e.get(Integer.valueOf(var0)));
   }

   static {
      b(true);

      for(a_4 var11 : values()) {
         e.put(Integer.valueOf(var11.d), var11);
      }

   }

   public static void b(boolean var0) {
      b = var0;
   }

   public static boolean c() {
      return b;
   }

   public static boolean a() {
      boolean var0 = c();
      return true;
   }
}
