package net;

import viaversion.viaversion.api.protocol.ServerboundPacketType;

public enum xZ implements ServerboundPacketType {
   KEEP_ALIVE,
   CHAT_MESSAGE,
   INTERACT_ENTITY,
   PLAYER_MOVEMENT,
   PLAYER_POSITION,
   PLAYER_ROTATION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_DIGGING,
   PLAYER_BLOCK_PLACEMENT,
   HELD_ITEM_CHANGE,
   ANIMATION,
   ENTITY_ACTION,
   STEER_VEHICLE,
   CLOSE_WINDOW,
   CLICK_WINDOW,
   WINDOW_CONFIRMATION,
   CREATIVE_INVENTORY_ACTION,
   CLICK_WINDOW_BUTTON,
   UPDATE_SIGN,
   PLAYER_ABILITIES,
   TAB_COMPLETE,
   CLIENT_SETTINGS,
   CLIENT_STATUS,
   PLUGIN_MESSAGE,
   SPECTATE,
   RESOURCE_PACK_STATUS;
}
