package net.minecraft.client.renderer;

import net.minecraft.client.renderer.BlockModelRenderer$Orientation;
import net.minecraft.util.EnumFacing;

public enum BlockModelRenderer$EnumNeighborInfo {
   DOWN("DOWN", 0, new EnumFacing[]{EnumFacing.WEST, EnumFacing.EAST, EnumFacing.NORTH, EnumFacing.SOUTH}, 0.5F, true, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.SOUTH, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.SOUTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.NORTH, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.NORTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.NORTH, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.NORTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.SOUTH, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.SOUTH}),
   UP("UP", 1, new EnumFacing[]{EnumFacing.EAST, EnumFacing.WEST, EnumFacing.NORTH, EnumFacing.SOUTH}, 1.0F, true, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.SOUTH, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.SOUTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.NORTH, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.NORTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.NORTH, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.NORTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.SOUTH, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.SOUTH}),
   NORTH("NORTH", 2, new EnumFacing[]{EnumFacing.UP, EnumFacing.DOWN, EnumFacing.EAST, EnumFacing.WEST}, 0.8F, true, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.FLIP_WEST}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.FLIP_EAST}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.FLIP_EAST}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.FLIP_WEST}),
   SOUTH("SOUTH", 3, new EnumFacing[]{EnumFacing.WEST, EnumFacing.EAST, EnumFacing.DOWN, EnumFacing.UP}, 0.8F, true, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.WEST}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.FLIP_WEST, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.WEST, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.WEST}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.EAST}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.FLIP_EAST, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.EAST, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.EAST}),
   WEST("WEST", 4, new EnumFacing[]{EnumFacing.UP, EnumFacing.DOWN, EnumFacing.NORTH, EnumFacing.SOUTH}, 0.6F, true, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.SOUTH, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.SOUTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.NORTH, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.NORTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.NORTH, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.NORTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.SOUTH, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.SOUTH}),
   EAST("EAST", 5, new EnumFacing[]{EnumFacing.DOWN, EnumFacing.UP, EnumFacing.NORTH, EnumFacing.SOUTH}, 0.6F, true, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.SOUTH, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.SOUTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.NORTH, BlockModelRenderer$Orientation.FLIP_DOWN, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.DOWN, BlockModelRenderer$Orientation.NORTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.NORTH, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.FLIP_NORTH, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.NORTH}, new BlockModelRenderer$Orientation[]{BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.SOUTH, BlockModelRenderer$Orientation.FLIP_UP, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.FLIP_SOUTH, BlockModelRenderer$Orientation.UP, BlockModelRenderer$Orientation.SOUTH});

   protected final EnumFacing[] field_178276_g;
   protected final float field_178288_h;
   protected final boolean field_178289_i;
   protected final BlockModelRenderer$Orientation[] field_178286_j;
   protected final BlockModelRenderer$Orientation[] field_178287_k;
   protected final BlockModelRenderer$Orientation[] field_178284_l;
   protected final BlockModelRenderer$Orientation[] field_178285_m;
   private static final BlockModelRenderer$EnumNeighborInfo[] field_178282_n = new BlockModelRenderer$EnumNeighborInfo[6];
   private static final BlockModelRenderer$EnumNeighborInfo[] $VALUES = new BlockModelRenderer$EnumNeighborInfo[]{DOWN, UP, NORTH, SOUTH, WEST, EAST};
   private static final String b = "CL_00002516";
   private static final BlockModelRenderer$EnumNeighborInfo[] $VALUES$ = new BlockModelRenderer$EnumNeighborInfo[]{DOWN, UP, NORTH, SOUTH, WEST, EAST};

   private BlockModelRenderer$EnumNeighborInfo(String var3, int var4, EnumFacing[] var5, float var6, boolean var7, BlockModelRenderer$Orientation[] var8, BlockModelRenderer$Orientation[] var9, BlockModelRenderer$Orientation[] var10, BlockModelRenderer$Orientation[] var11) {
      this.field_178276_g = var5;
      this.field_178288_h = var6;
      this.field_178289_i = var7;
      this.field_178286_j = var8;
      this.field_178287_k = var9;
      this.field_178284_l = var10;
      this.field_178285_m = var11;
   }

   public static BlockModelRenderer$EnumNeighborInfo getNeighbourInfo(EnumFacing var0) {
      return field_178282_n[var0.getIndex()];
   }

   static {
      field_178282_n[EnumFacing.DOWN.getIndex()] = DOWN;
      field_178282_n[EnumFacing.UP.getIndex()] = UP;
      field_178282_n[EnumFacing.NORTH.getIndex()] = NORTH;
      field_178282_n[EnumFacing.SOUTH.getIndex()] = SOUTH;
      field_178282_n[EnumFacing.WEST.getIndex()] = WEST;
      field_178282_n[EnumFacing.EAST.getIndex()] = EAST;
   }
}
